// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArv2v1MAvw2hf50Zyido3-fLm0VLzUddo',
    appId: '1:893455818215:android:9eca815d8df0a0838f7142',
    messagingSenderId: '893455818215',
    projectId: 'push-app-notifications-cac04',
    storageBucket: 'push-app-notifications-cac04.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpfI9MZiCbKdqlamCH9kTH3l8UawYwWVY',
    appId: '1:893455818215:ios:f6a5af8b8933586b8f7142',
    messagingSenderId: '893455818215',
    projectId: 'push-app-notifications-cac04',
    storageBucket: 'push-app-notifications-cac04.appspot.com',
    iosBundleId: 'com.example.pushAppNotification',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyApKbH_p9WXU79FFfYl6rykLW3fHljJmIE',
    appId: '1:893455818215:web:db489d8e4b5abc538f7142',
    messagingSenderId: '893455818215',
    projectId: 'push-app-notifications-cac04',
    authDomain: 'push-app-notifications-cac04.firebaseapp.com',
    storageBucket: 'push-app-notifications-cac04.appspot.com',
  );

}